#!/bin/bash

#
# Copyright (C) 2013 Dan Fruehauf <malkodan@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

log() {
	# log to a log file at /var/log/backups/backups.log
	logfile /var/log/backups/backups.log
}

backup() {
	# pull a backup from remote host, it'll be stored in
	# /var/backup/remote-host
	rsync remote-host root@localhost:/var/backups/*
}

store() {
	# store backup locally, will be in /var/backups/remote-host
	# avoid appending a timestamp to the backup as we assume it'll already have
	# one, so we eliminate the hierarchy
	cp_no_timestamp /var/backups

	# cycle backups after they've been pulled, leaving 14 backups in total
	cycle /tmp/backups2/remote-host 14
}
